name: black-linter

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jpetrucciani/black-check@23.12.1
      with:
        black_flags: '-S'
