name: Contributors

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  contributors:
    runs-on: ubuntu-latest
    if: github.repository == 'doocs/leetcode'
    steps:
      - uses: wow-actions/contributors-list@v1
        name: Update contributors
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          svgPath: images/contributors.svg
          svgWidth: 890
          commitMessage: "chore: auto update contributors"
