name: Lint Code Base

on: [push, pull_request]

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      # Checkout the code base
      - name: Checkout Code
        uses: actions/checkout@v2
        
      # Run Linter against code base
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.0
