name: Sync

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to gitee.com
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
      with:
          source-repo: "git@github.com:doocs/leetcode.git"
          destination-repo: "git@gitee.com:Doocs/leetcode.git"

    - name: Set ssh environment
      env:
        SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com > ~/.ssh/known_hosts
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
        git config --global user.name "yanglbme"
        git config --global user.email "szuyanglb@outlook.com"
    
    - name: Sync to coding.net
      run: |
        cd /tmp
        git clone git@github.com:doocs/leetcode.git leetcode
        cd leetcode
        git checkout master
        git remote add coding git@e.coding.net:doocs/leetcode.git
        git push coding master